{{- if .Values.configSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.configSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
